### ISSUE TITLE
Hardcoded command line order vs. getopts

### ISSUE THREAD

**Issue by samueltardieu** [Neilpang/le#27]
I feel like we're getting to the limits of harcoded arguments (with `no` meaning default) *vs.* optional arguments. Wouldn't it be easier to give "-c certfile", "-C cafile", etc.? Especially when bash has a builtin `getopts`.

**Comment by lucasRolff** [comment]
Agreed `getopts` would be nice

**Comment by Neilpang** [comment]
I agree. 
I'm now on the new DNS challenge, automatically  with CloudFlare DNS apis.  
So,  getopts would be soon.

**Comment by raunsbaekdk** [comment]
@Neilpang Do you have an ETA on Cloudflare integration - or maybe some code we can contribute to?

**Comment by Neilpang** [comment]
@raunsbaekdk 

Yes,  just yesterday, Let's encrypt fixed the bug, so that cloudflare dns can work with let's encrypt.

I just checked in a new branch  "dnsapi",   cloudflare api is there, but not working yet. I need some more time to debug.

If you guys have a domain in godaddy, it would be great if you can test godaddy api.

Thanks.

**Comment by Neilpang** [comment]
@raunsbaekdk 

Cloudflare api  is working now.

And we support any custom api.

Please check the readme.

**Comment by Neilpang** [comment]
It's supported in V2.0 now.  
a63b05a9e761eb7d89811be4b714d818dd7c76c0

Please try again.
