### ISSUE TITLE
Is there a rationale behind using "cp -p" instead of "mv"

### ISSUE THREAD

**Issue by BlueAnanas** [Neilpang/le#85]
in installcert? On some filesystems this return errors like 
`cp:  preserving permissions for ‘/etc/pve/local/pve-ssl.pem.bak’: Function not implemented`

no harm done and permissions are in fact preserved, but we all don't like error messages, are we?

I would wait with a PR after decision on #84 so there won't be merge conflicts

**Comment by Neilpang** [comment]
Yes,  I have a lot of servers that run PVE, and I also noticed the "-p" option is not implemented on PVE yet.

 here are several concerns. 

1.  We can not use `mv`.   Just think about if the original file "/etc/pve/local/pve-ssl.pem" is a symbol link, instead of a real file.   What will happen if we move ?  If there are some other symbol links referring to the same original file, all of them will get updated in current implementation. 

2. If we use `mv`,  we will need to `create`  the new file.  Then there will be  permission problems.  Do we have `write` permission in the parent folder ?   Even if we are root(or has permission to create file in  the parent folder),  we will also need to deal with the permissions of the new created file too.  Something like `chown` or `chgrp` or `chmod` etc,  bla, bla, bla.....   
For example the permissions is like:
```
-rw-r----- 1 root www-data 1.8K Jan 13 13:23 /etc/pve/local/pve-ssl.pem
```
We should need always keep the exactly same modes of the new file,  which would bring us a lot of troubles, especially when we want to be portable to many different platforms(for different servers: apache, nginx, exim4 and dovecot etc. )

However, if we don't move the original file, we only need `write` access to the original file, which is goooooood to me.  That's the minimum  permission we need.

3. For PVE issue, I do see this issue before, but it doesn't matter at all right ?


4. Another plan.  I was think about to move the ".bak" file to the `.le/domain.com/` folder. Which could be more safe.

what do you think?

**Comment by BlueAnanas** [comment]
I definitely think that the rationale using "cp -p" is imperative:

- using mv will lead to too much things left to check to prevent hiccups
- the cp is complaining but effectively doing it anyway on a loop fs.
- it seem that the cp won't fail to create a file with the expected contents even if the attributes wouldn't be set to the right values on other fs
- we won't die from an error message :-)

moving the .bak file to the .le/domain.com/ folder would be rewarding only if there would be some sort of a rollback `command ` - which is fairly complex to implement in a reliable way.
In the rare cases a rollback has to be done manually now, it is pretty useful that the .bak files are in the same folder as the files because there is no need to search for them.
